package com.coreman2200.ringstrings.domain.symbol.entitysymbol.grouped

import com.coreman2200.ringstrings.domain.symbol.symbolinterface.ISymbolID
import java.util.*

/**
 * TagSymbols
 * Simple test tags to test functionality of Tags/tagging systems before implementation is designed..
 *
 * Created by Cory Higginbottom on 11/3/15
 * http://github.com/coreman2200
 *
 * Licensed under the GNU General Public License (GPL), Version 2.0.
 * You may not use this file except in compliance with this License.
 *
 * You may obtain a copy of the GPLv2 License at
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 */
enum class TagSymbols : ITagID {
    VENUS, MARS, JUPITER, SATURN, URANUS, NEPTUNE, PLUTO, RETROGRADE, ARIES, TAURUS, GEMINI, CANCER, LEO, VIRGO, LIBRA, SCORPIO, SAGITTARIUS, CAPRICORN, AQUARIUS, PISCES, FIRE, AIR, WATER, VOID, ZERO, ONE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, LIFE_JOURNEY, TALENTS, DESTINY, INFLUENCE, PERSONALITY, LESSONS, THINKING, TWENTY__SEVEN_YEARS, ORIENTATION, SELF_EXPRESSION, EARLY_STAGES, MIDDLE_STAGES, PERSISTENT, LATER_STAGES, ANNUAL, DAILY, MONTHLY, EVEN, ODD, SUN, MOON, MERCURY, ACHIEVEMENT, ABILITY, ACTION, ACTIVITY, ADAPTABILITY, ADVENTUROUS, AGGRESSION, ALL, ALTRUISM, AMBITION, APPLICATION, ASSERTION, ATTAINMENT, ATTRACTIONS, AUTHORITY, AWARENESS, BALANCE, BEAUTY, BEGINNING, BEING, BOUNDARY, BUILDING, BUSINESS, CAREER, CENTER, CHALLENGE, CHANGES, CHILDREN, CHOICE, COMMITMENT, COMMUNICATION, COMPASSION, COMPLETION, CONCENTRATION, CONCLUSION, CONNECTION, CONSOLIDATION, CONTRACTS, CONTRAST, CREATION, CREATIVITY, CURIOSITY, CYCLE, DARKNESS, DEFENSE_MECHANISM, DENIAL, DEED, DEPTH, DESIRE, DETERMINATION, DISCIPLINE, DISCOVERY, DIVERSITY, DIVINATION, DOMESTIC_ISSUES, DOMINANCE, DUALITY, EARTH, EDUCATION, EGO, ELEGANCE, EMOTION, ENERGY, ENLIGHTENMENT, ETHICS, EVALUATION, EXPANSION, EXPECTATIONS, EXPLORATION, EXPRESSION, EXTREMES, FAIRNESS, FAITH, FEAR, FERTILITY, FIRST_IMPRESSION, FOCUS, FOUNDATION, FREEDOM, FREE__SPIRIT, GAIN, GATEWAY, GOALS, GREATNESS, GROUPS, GROWTH, HABITS, HARMONY, HEALTH, HUMANITY, ILLUSION, IMAGINATION, INDIVIDUALITY, INNER_GOAL, INNOVATION, INSIGHT, INSPIRATION, INTELLIGENCE, INTERPRETATION, INTIMACY, INTUITION, IRRATIONAL, ISOLATION, JOURNEY, JUSTICE, KINDNESS, KNOWLEDGE, LEADERSHIP, LOSS, LOVE, MARRIAGE, MASTER_NUMBER, MATERIALISM, MATURITY, MORALITY, MOTHERHOOD, MOTIVATION, MOVEMENT, MYSTERY, MYSTICISM, NURTURING, OPPOSITION, OPTIMISM, ORGANIZING, PARTNERS, PASSION, PHYSICALITY, PLEASURE, POSITION, POWER, PRACTICALITY, PRIDE, PROCESS, PROGRESSION, PROSPERITY, PROTECTING, PURPOSE, RAISED_CONSCIOUSNESS, RARE, RATIONALITY, REALITY, REASON, REBIRTH, RECHARGING, RECLAMATION, RENEWAL, REPUTATION, RESPONSIBILITY, RESTRICTION, REVOLUTIONARY, RHYTHM, ROMANCE, SEDUCTION, SELF__IMAGE, SENSITIVITY, SEXUALITY, SHARING, SOCIAL_STATUS, SPARK, SPIRITUALITY, STABILITY, STRENGTH, STRUCTURE, SUFFERING, TANGIBILITY, TASTES, TRANSFORMATION, TRAVEL, TRUTH, UNDERSTANDING, UNIQUE, UNITY, UPBRINGING, VALUES, VISION, VITALITY, WHOLENESS, WISDOM, WORK, WORLDLY, THE_WOUNDED_HEALER, WRITING;

    override fun toString(): String {
        return name.replace("__".toRegex(), "-").replace("_".toRegex(), " ").lowercase(Locale.US)
    }
}

interface IEntityID : ISymbolID
interface ITagID : IEntityID
