package com.coreman2200.ringstrings.domain

import android.content.Context
import com.coreman2200.ringstrings.domain.input.numerology.numbersystem.NumberSystemType
import java.util.*

/**
 * TestDefaultDataBundles
 * Util builders and immutable data bundles for use while testing..
 *
 * Created by Cory Higginbottom on 2/19/16
 * http://github.com/coreman2200
 *
 * Licensed under the GNU General Public License (GPL), Version 2.0.
 * You may not use this file except in compliance with this License.
 *
 * You may obtain a copy of the GPLv2 License at
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 */
object MockDefaultDataBundles {

    private val DFLT_NUMBERSYSTEM = NumberSystemType.PYTHAGOREAN
    private const val DFLT_MAX_ORB = 2.0
    private const val MIN_LAT = -60.0
    private const val MAX_LAT = 120.0
    private const val MIN_LON = -180.0
    private const val MAX_LON = 360.0

    ///////////////////////////// Defined test profiles
    val testProfileBundleCoryH = produceCoryHProfileBundle()
    private fun produceCoryHProfileBundle(): ProfileData {
        val fullname = produceProfileName("Cory", "Michael", "Higginbottom")
        val displayname = "Cory H"

        // Describes birth placement
        val birthdate = GregorianCalendar(1986, 11, 23, 17, 36)
        val tz = TimeZone.getTimeZone("GMT-5")
        birthdate.timeZone = tz
        val birthloc = produceProfileLocation(42.21, -71.03, 9.48)
        val birthplacement = produceProfilePlacement(birthloc, birthdate.timeInMillis, tz.id)
        return ProfileData(
            id = generateProfileId(),
            name = fullname,
            displayName = displayname,
            birthPlacement = birthplacement,
            currentPlacement = generateRandomProfilePlacement()
        )
    }

    private fun produceProfileName(vararg segments: String): List<String> {
        return listOf(*segments)
    }

    private fun produceProfileLocation(lat: Double, lon: Double, alt: Double): GeoLocation {
        return GeoLocation(lat, lon, alt)
    }

    private fun produceProfilePlacement(
        loc: GeoLocation,
        timestamp: Long,
        timezone: String
    ): GeoPlacement {
        return GeoPlacement(loc,timestamp, timezone)
    }

    ////////////////////////////////////////// Randomly Generated Profiles
    fun generateRandomProfile(): ProfileData {
        return ProfileData(
            id =  generateProfileId(),
            name =  generateRandomProfileName(),
            birthPlacement = generateRandomProfilePlacement(),
            currentPlacement = generateRandomProfilePlacement()
            )
    }

    private fun generateProfileId(): Int {
        return 1 + (Math.random() * (2 shl 20)).toInt()
    }

    private fun generateRandomProfileName(): List<String> {
        val testName: MutableList<String> = ArrayList()
        testName.add(NAMES[(Math.random() * NAMES.size).toInt()])
        testName.add(NAMES[(Math.random() * NAMES.size).toInt()])
        testName.add(NAMES[(Math.random() * NAMES.size).toInt()] + LAST_APPENDS[(Math.random() * LAST_APPENDS.size).toInt()])
        return testName
    }

    private fun generateRandomProfilePlacement(): GeoPlacement {
        val tz = TimeZone.getDefault()
        return GeoPlacement(generateRandomLocation(),
            generateRandomTimeStamp(tz),
            tz.id)
    }

    private fun generateRandomTimeStamp(tz: TimeZone = TimeZone.getDefault()): Long {
        val mTestDate = GregorianCalendar(Locale.US)
        mTestDate.timeZone = tz
        mTestDate[1800 + (Math.random() * 600).toInt(), (Math.random() * 12).toInt(), (Math.random() * 31).toInt(), (Math.random() * 24).toInt()] =
            (Math.random() * 60).toInt()
        return mTestDate.timeInMillis
    }

    private fun generateRandomLocation(): GeoLocation {
        return GeoLocation(MIN_LAT + Math.random() * MAX_LAT,
            MIN_LON + Math.random() * MAX_LON,
            Math.random() * 1000
        )
    }

    /////////////////////// Settings for RingStrings app. (Context required either to generate or to load(todo))
    fun produceDefaultAppSettingsBundle(context: Context?): AppSettings {
        return AppSettings(produceAstroSettings("/ephe/"), produceNumSettings())
    }

    private fun produceAstroSettings(dir: String): AstrologySettings {
        return AstrologySettings(DFLT_MAX_ORB,dir)
    }

    private fun produceNumSettings(): NumerologySettings {
        return NumerologySettings()
    }

    enum class TEST_PROFILES {
        CoryH
    }

    private val NAMES = arrayOf(
        "Nicola",
        "Karen",
        "Fiona",
        "Susan",
        "Claire",
        "Sharon",
        "Angela",
        "Gillian",
        "Julie",
        "Michelle",
        "Jacqueline",
        "Amanda",
        "Tracy",
        "Louise",
        "Jennifer",
        "Alison",
        "Sarah",
        "Donna",
        "Caroline",
        "Elaine",
        "Lynn",
        "Margaret",
        "Elizabeth",
        "Lesley",
        "Deborah",
        "Pauline",
        "Lorraine",
        "Laura",
        "Lisa",
        "Tracey",
        "Carol",
        "Linda",
        "Lorna",
        "Catherine",
        "Wendy",
        "Lynne",
        "Yvonne",
        "Pamela",
        "Kirsty",
        "Jane",
        "Emma",
        "Joanne",
        "Heather",
        "Suzanne",
        "Anne",
        "Diane",
        "Helen",
        "Victoria",
        "Dawn",
        "Mary",
        "Samantha",
        "Marie",
        "Kerry",
        "Ann",
        "Hazel",
        "Christine",
        "Gail",
        "Andrea",
        "Clare",
        "Sandra",
        "Shona",
        "Kathleen",
        "Paula",
        "Shirley",
        "Denise",
        "Melanie",
        "Patricia",
        "Audrey",
        "Ruth",
        "Jill",
        "Lee",
        "Leigh",
        "Catriona",
        "Rachel",
        "Morag",
        "Kirsten",
        "Kirsteen",
        "Katrina",
        "Joanna",
        "Lynsey",
        "Cheryl",
        "Debbie",
        "Maureen",
        "Janet",
        "Aileen",
        "Arlene",
        "Zoe",
        "Lindsay",
        "Stephanie",
        "Judith",
        "Mandy",
        "Jillian",
        "Mhairi",
        "Barbara",
        "Carolyn",
        "Gayle",
        "Maria",
        "Valerie",
        "Christina",
        "Marion",
        "Nicola",
        "Karen",
        "Susan",
        "Claire",
        "Fiona",
        "Angela",
        "Sharon",
        "Gillian",
        "Julie",
        "Jennifer",
        "Michelle",
        "Louise",
        "Lisa",
        "Amanda",
        "Donna",
        "Tracy",
        "Alison",
        "Elaine",
        "Jacqueline",
        "Sarah",
        "Caroline",
        "Elizabeth",
        "Laura",
        "Lynn",
        "Deborah",
        "Lesley",
        "Margaret",
        "Joanne",
        "Pauline",
        "Lorraine",
        "Carol",
        "Kirsty",
        "Yvonne",
        "Lorna",
        "Emma",
        "Lynne",
        "Tracey",
        "Heather",
        "Catherine",
        "Pamela",
        "Helen",
        "Linda",
        "Jane",
        "Anne",
        "Kerry",
        "Suzanne",
        "Wendy",
        "Victoria",
        "Diane",
        "Mary",
        "Dawn",
        "Clare",
        "Gail",
        "Paula",
        "Ann",
        "Shona",
        "Hazel",
        "Christine",
        "Andrea",
        "Samantha",
        "Marie",
        "Lynsey",
        "Sandra",
        "Denise",
        "Lee",
        "Kelly",
        "Gayle",
        "Debbie",
        "Jill",
        "Kathleen",
        "Patricia",
        "Joanna",
        "Catriona",
        "Shirley",
        "Ruth",
        "Zoe",
        "Leigh",
        "Rachel",
        "Melanie",
        "Kirsteen",
        "Aileen",
        "Christina",
        "Janet",
        "Katrina",
        "Stephanie",
        "Audrey",
        "Kirsten",
        "Arlene",
        "Maureen",
        "Morag",
        "Marion",
        "Mhairi",
        "Allison",
        "Cheryl",
        "Maria",
        "Kim",
        "Anna",
        "Lindsay",
        "Rebecca",
        "Katherine",
        "Mandy",
        "Nicola",
        "Karen",
        "Claire",
        "Angela",
        "Fiona",
        "Susan",
        "Jennifer",
        "Julie",
        "Gillian",
        "Michelle",
        "Sharon",
        "Sarah",
        "Louise",
        "Donna",
        "Laura",
        "Amanda",
        "Alison",
        "Lisa",
        "Caroline",
        "Kirsty",
        "Jacqueline",
        "Elaine",
        "Lesley",
        "Lynn",
        "Deborah",
        "Elizabeth",
        "Joanne",
        "Emma",
        "Tracy",
        "Lorraine",
        "Lynne",
        "Margaret",
        "Heather",
        "Carol",
        "Lorna",
        "Pauline",
        "Kelly",
        "Helen",
        "Catherine",
        "Linda",
        "Victoria",
        "Suzanne",
        "Kerry",
        "Pamela",
        "Lee",
        "Wendy",
        "Jane",
        "Yvonne",
        "Tracey",
        "Anne",
        "Clare",
        "Mary",
        "Diane",
        "Christine",
        "Lynsey",
        "Samantha",
        "Shona",
        "Andrea",
        "Marie",
        "Gail",
        "Melanie",
        "Dawn",
        "Ann",
        "Paula",
        "Jill",
        "Ruth",
        "Leigh",
        "Hazel",
        "Debbie",
        "Joanna",
        "Denise",
        "Lindsay",
        "Gayle",
        "Patricia",
        "Catriona",
        "Kathleen",
        "Sandra",
        "Leanne",
        "Stephanie",
        "Rachel",
        "Katrina",
        "Shirley",
        "Kirsteen",
        "Janet",
        "Arlene",
        "Zoe",
        "Jillian",
        "Anna",
        "Judith",
        "Mhairi",
        "Natalie",
        "Audrey",
        "Carolyn",
        "Morag",
        "Aileen",
        "Cheryl",
        "Rebecca",
        "Allison",
        "Barbara",
        "Mandy",
        "Claire",
        "Nicola",
        "Karen",
        "Angela",
        "Gillian",
        "Fiona",
        "Jennifer",
        "Laura",
        "Susan",
        "Julie",
        "Michelle",
        "Lisa",
        "Sharon",
        "Louise",
        "Sarah",
        "Tracy",
        "Donna",
        "Kelly",
        "Kirsty",
        "Amanda",
        "Alison",
        "Joanne",
        "Caroline",
        "Emma",
        "Jacqueline",
        "Elaine",
        "Elizabeth",
        "Lynne",
        "Lesley",
        "Deborah",
        "Kerry",
        "Victoria",
        "Carol",
        "Catherine",
        "Lynn",
        "Pauline",
        "Margaret",
        "Lorna",
        "Lynsey",
        "Lorraine",
        "Linda",
        "Suzanne",
        "Tracey",
        "Heather",
        "Yvonne",
        "Jane",
        "Dawn",
        "Mary",
        "Helen",
        "Anne",
        "Wendy",
        "Lee",
        "Pamela",
        "Jill",
        "Lindsay",
        "Clare",
        "Christine",
        "Diane",
        "Leigh",
        "Samantha",
        "Shona",
        "Joanna",
        "Ruth",
        "Debbie",
        "Gail",
        "Marie",
        "Andrea",
        "Paula",
        "Kathleen",
        "Catriona",
        "Katrina",
        "Denise",
        "Melanie",
        "Ann",
        "Sandra",
        "Gayle",
        "Hazel",
        "Jillian",
        "Stephanie",
        "Rachel",
        "Kim",
        "Natalie",
        "Katherine",
        "Patricia",
        "Leanne",
        "Cheryl",
        "Mhairi",
        "Morag",
        "Arlene",
        "Zoe",
        "Kathryn",
        "Aileen",
        "Ashley",
        "Judith",
        "Anna",
        "Frances",
        "Janet",
        "Lucy",
        "Vicky",
        "Christina",
        "Kirsten",
        "Rebecca",
        "Nicola",
        "Claire",
        "Laura",
        "Karen",
        "Michelle",
        "Louise",
        "Jennifer",
        "Fiona",
        "Lisa",
        "Gillian",
        "Angela",
        "Julie",
        "Susan",
        "Sarah",
        "Kelly",
        "Donna",
        "Sharon",
        "Emma",
        "Caroline",
        "Alison",
        "Joanne",
        "Tracy",
        "Kirsty",
        "Lynne",
        "Amanda",
        "Elaine",
        "Jacqueline",
        "Lesley",
        "Kerry",
        "Elizabeth",
        "Lynn",
        "Margaret",
        "Deborah",
        "Catherine",
        "Heather,",
        "David",
        "John",
        "Paul",
        "Mark",
        "James",
        "Andrew",
        "Scott",
        "Steven",
        "Robert",
        "Stephen",
        "William",
        "Craig",
        "Michael",
        "Stuart",
        "Christopher",
        "Alan",
        "Colin",
        "Brian",
        "Kevin",
        "Gary",
        "Richard",
        "Derek",
        "Martin",
        "Thomas",
        "Neil",
        "Barry",
        "Ian",
        "Jason",
        "Iain",
        "Gordon",
        "Alexander",
        "Graeme",
        "Peter",
        "Darren",
        "Graham",
        "George",
        "Kenneth",
        "Allan",
        "Simon",
        "Douglas",
        "Keith",
        "Lee",
        "Anthony",
        "Grant",
        "Ross",
        "Jonathan",
        "Gavin",
        "Nicholas",
        "Joseph",
        "Stewart",
        "Daniel",
        "Edward",
        "Matthew",
        "Donald",
        "Fraser",
        "Garry",
        "Malcolm",
        "Charles",
        "Duncan",
        "Alistair",
        "Raymond",
        "Philip",
        "Ronald",
        "Ewan",
        "Ryan",
        "Francis",
        "Bruce",
        "Patrick",
        "Alastair",
        "Bryan",
        "Marc",
        "Jamie",
        "Hugh",
        "Euan",
        "Gerard",
        "Sean",
        "Wayne",
        "Adam",
        "Calum",
        "Alasdair",
        "Robin",
        "Greig",
        "Angus",
        "Russell",
        "Cameron",
        "Roderick",
        "Norman",
        "Murray",
        "Gareth",
        "Dean",
        "Eric",
        "Adrian",
        "Gregor",
        "Samuel",
        "Gerald",
        "Henry",
        "Justin",
        "Benjamin",
        "Shaun",
        "Callum",
        "Campbell",
        "Frank",
        "Roy",
        "Timothy",
        "David",
        "John",
        "Paul",
        "James",
        "Mark",
        "Scott",
        "Andrew",
        "Steven",
        "Robert",
        "Stephen",
        "Craig",
        "Christopher",
        "Alan",
        "Michael",
        "Stuart",
        "William",
        "Kevin",
        "Colin",
        "Brian",
        "Derek",
        "Neil",
        "Richard",
        "Gary",
        "Barry",
        "Martin",
        "Thomas",
        "Ian",
        "Gordon",
        "Kenneth",
        "Alexander",
        "Graeme",
        "Peter",
        "Iain",
        "Graham",
        "Jason",
        "George",
        "Allan",
        "Keith",
        "Darren",
        "Simon",
        "Douglas",
        "Ross",
        "Stewart",
        "Lee",
        "Grant",
        "Nicholas",
        "Joseph",
        "Gavin",
        "Anthony",
        "Jonathan",
        "Daniel",
        "Fraser",
        "Matthew",
        "Donald",
        "Malcolm",
        "Alistair",
        "Edward",
        "Raymond",
        "Charles",
        "Philip",
        "Bruce",
        "Garry",
        "Jamie",
        "Ryan",
        "Bryan",
        "Francis",
        "Alastair",
        "Duncan",
        "Patrick",
        "Ronald",
        "Alasdair",
        "Ewan",
        "Marc",
        "Wayne",
        "Hugh",
        "Robin",
        "Sean",
        "Calum",
        "Euan",
        "Adam",
        "Russell",
        "Cameron",
        "Gerard",
        "Murray",
        "Norman",
        "Angus",
        "Greig",
        "Justin",
        "Gregor",
        "Gerald",
        "Roderick",
        "Roy",
        "Benjamin",
        "Timothy",
        "Dean",
        "Samuel",
        "Greg",
        "Shaun",
        "Adrian",
        "Campbell",
        "David",
        "John",
        "Paul",
        "James",
        "Andrew",
        "Steven",
        "Scott",
        "Mark",
        "Robert",
        "Stephen",
        "Craig",
        "Christopher",
        "Stuart",
        "Alan",
        "William",
        "Michael",
        "Kevin",
        "Colin",
        "Brian",
        "Derek",
        "Neil",
        "Richard",
        "Martin",
        "Gary",
        "Ross",
        "Thomas",
        "Ian",
        "Iain",
        "Barry",
        "Gordon",
        "Graeme",
        "Graham",
        "Alexander",
        "Peter",
        "Kenneth",
        "Simon",
        "Allan",
        "Darren",
        "George",
        "Douglas",
        "Jason",
        "Lee",
        "Gavin",
        "Anthony",
        "Jonathan",
        "Stewart",
        "Jamie",
        "Keith",
        "Matthew",
        "Joseph",
        "Daniel",
        "Edward",
        "Nicholas",
        "Grant",
        "Ryan",
        "Philip",
        "Alistair",
        "Donald",
        "Charles",
        "Duncan",
        "Garry",
        "Malcolm",
        "Raymond",
        "Bryan",
        "Ewan",
        "Fraser",
        "Alastair",
        "Euan",
        "Patrick",
        "Bruce",
        "Ronald",
        "Greig",
        "Hugh",
        "Francis",
        "Gerard",
        "Russell",
        "Alasdair",
        "Adam",
        "Marc",
        "Sean",
        "Benjamin",
        "Gregor",
        "Calum",
        "Wayne",
        "Robin",
        "Roderick",
        "Murray",
        "Greg",
        "Angus",
        "Cameron",
        "Gerald",
        "Shaun",
        "Samuel",
        "Timothy",
        "Liam",
        "Campbell",
        "Gareth",
        "Niall",
        "Dean",
        "Justin",
        "David",
        "John",
        "Paul",
        "James",
        "Andrew",
        "Steven",
        "Scott",
        "Mark",
        "Robert",
        "Christopher",
        "Craig",
        "Stuart",
        "Kevin",
        "Alan",
        "Michael",
        "Stephen",
        "William",
        "Colin",
        "Brian",
        "Neil",
        "Richard",
        "Ross",
        "Thomas",
        "Gary",
        "Derek",
        "Iain",
        "Gordon",
        "Graeme",
        "Martin",
        "Barry",
        "Gavin",
        "Ian",
        "Kenneth",
        "Alexander",
        "Peter",
        "Graham",
        "Allan",
        "Darren",
        "Jamie",
        "Simon",
        "Lee",
        "George",
        "Keith",
        "Stewart",
        "Douglas",
        "Jonathan",
        "Matthew",
        "Daniel",
        "Grant",
        "Joseph",
        "Jason",
        "Anthony"
    )
    private val LAST_APPENDS =
        arrayOf("s", "enstein", "lion", "son", "short", "dumdiddly", "inions", "idious-Law")
}